version: 2

before:
  hooks:
    - sh -c "cd frontend && npm ci && npm run build"
    - go mod tidy

builds:
  - id: gp
    binary: gp
    main: .
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - id: gp
    ids: [gp]
    formats: [tar.gz]
    format_overrides:
      - goos: windows
        formats: [zip]
    files:
      - README.md
      - LICENSE

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  github:
    owner: hiroyukim
    name: green-pepper
